# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov  2 18:02:19 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(821, 674)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setWindowTitle(_fromUtf8("Urban Terror Demo-Screenshot C0nc4t3n4t0r"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.demosList = QtGui.QListWidget(self.centralwidget)
        self.demosList.setMinimumSize(QtCore.QSize(200, 0))
        self.demosList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.demosList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.demosList.setFrameShadow(QtGui.QFrame.Plain)
        self.demosList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.demosList.setAlternatingRowColors(True)
        self.demosList.setProperty(_fromUtf8("isWrapping"), False)
        self.demosList.setWordWrap(True)
        self.demosList.setObjectName(_fromUtf8("demosList"))
        self.horizontalLayout.addWidget(self.demosList)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.screen = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setTextFormat(QtCore.Qt.AutoText)
        self.screen.setScaledContents(True)
        self.screen.setObjectName(_fromUtf8("screen"))
        self.verticalLayout_2.addWidget(self.screen)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.createArchive = QtGui.QPushButton(self.centralwidget)
        self.createArchive.setObjectName(_fromUtf8("createArchive"))
        self.horizontalLayout_2.addWidget(self.createArchive)
        self.viewAllScreenshots = QtGui.QPushButton(self.centralwidget)
        self.viewAllScreenshots.setObjectName(_fromUtf8("viewAllScreenshots"))
        self.horizontalLayout_2.addWidget(self.viewAllScreenshots)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Demos = QtGui.QMenu(self.menubar)
        self.menu_Demos.setObjectName(_fromUtf8("menu_Demos"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Options = QtGui.QAction(MainWindow)
        self.action_Options.setObjectName(_fromUtf8("action_Options"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Update_list = QtGui.QAction(MainWindow)
        self.action_Update_list.setObjectName(_fromUtf8("action_Update_list"))
        self.action_About_urtdsc = QtGui.QAction(MainWindow)
        self.action_About_urtdsc.setObjectName(_fromUtf8("action_About_urtdsc"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menu_File.addAction(self.action_Options)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Demos.addAction(self.action_Update_list)
        self.menu_Help.addAction(self.action_About_urtdsc)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Demos.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.demosList.setSortingEnabled(False)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.screen.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.createArchive.setText(QtGui.QApplication.translate("MainWindow", "Create Archive...", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllScreenshots.setText(QtGui.QApplication.translate("MainWindow", "View all screenshots", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Demos.setTitle(QtGui.QApplication.translate("MainWindow", "&Demos", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Options.setText(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Update_list.setText(QtGui.QApplication.translate("MainWindow", "&Update list...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_urtdsc.setText(QtGui.QApplication.translate("MainWindow", "&About urtdsc...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About &Qt...", None, QtGui.QApplication.UnicodeUTF8))

